gallery/urls.py
from django.urls import path

from gallery.views import gallery_view #ImageView, ImageList, AlbumView, AlbumList, ImageCreate

app_name = 'gallery'
urlpatterns = [
    path('', gallery_view, name="gallery")
    #path('', AlbumList.as_view(), name='album_list'),
    #path('images/', ImageList.as_view(), name='image_list'),
    #path('image/<int:pk>/<slug>', ImageView.as_view(), name='image_detail'),
    #path('upload/', ImageCreate.as_view(), name='image_upload'),
    #path('album/<int:pk>/<slug>/', AlbumView.as_view(), name='album_detail'),
    #path('album/<int:apk>/<int:pk>/<slug>', ImageView.as_view(), name='album_image_detail'),
]

myblog/urls.py
from allauth.account import views as allauth_views
from django.conf.urls import url
from django.conf import settings
from django.views.static import serve
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from filebrowser.sites import site

handler404 = 'myposts.views.handler404'
handler500 = 'myposts.views.handler500'

urlpatterns = [
    url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
    path('admin/filebrowser/', site.urls),
	path('tinymce/',include('tinymce.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('accounts/login/', allauth_views.LoginView.as_view(template_name='login.html'), name='account_login'),
    path('', include('newsletter.urls', namespace = 'signups')),
    path('',include('myposts.urls', namespace = 'myposts')),
    path('',include('profiles.urls', namespace ='profiles')),
    path('',include('weatherapp.urls', namespace='weatherapp')),
    path('gallery/', include('gallery.urls')),
    path('',include('contactus.urls', namespace='contactus'))
]

myposts/urls.py
"""from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views
from .views import(
		index, 
		blog,
		search, 
		sort_by_category,
		post_detail,
		post_create,
		post_update,
		#PostUpdateView,
		post_delete
		#PostDeleteView
	) 


app_name = 'myposts'

handler404 = views.handler404 
handler500 = views.handler500

urlpatterns = [
	path('', index, name = 'index'),
	path('blog/', blog, name = 'post-list'),
	path('search/', search, name = 'search'),
	path('category/', sort_by_category, name = 'category'),
	path('post/<int:id>/', post_detail, name = 'post-detail'),
	path("create/", post_create, name ='post-create'),
	path("post/<int:id>/update", post_update, name = 'post-update'),
	path("post/<int:id>/delete", post_delete, name = 'post-delete')
]

urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
"""

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from .views import (
    index,
    search,
    blog,
    sort_by_category,
    data_deletion,
    #post_detail,
    #post_create,
    #post_update,
    #post_delete,
    PostDetailView,
    PostCreateView,
    PostUpdateView,
    PostDeleteView
)

app_name = 'myposts'


urlpatterns = [
    path('', index, name = 'index'),
    path('blog/', blog, name='post-list'),
    path('search/', search, name='search'),
    #path('category/', sort_by_category, name = 'category'),
    path('category/<category>', sort_by_category, name = 'category'),
    # path('create/', post_create, name='post-create'),
    path('data-deletion', data_deletion, name='data-deletion'),
    path('create/', PostCreateView.as_view(), name='post-create'),
    # path('post/<id>/', post_detail, name='post-detail'),
    path('post/<pk>/', PostDetailView.as_view(), name='post-detail'),
    # path('post/<id>/update/', post_update, name='post-update'),
    path('post/<pk>/update/', PostUpdateView.as_view(), name='post-update'),
    # path('post/<id>/delete/', post_delete, name='post-delete'),
    path('post/<pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
]

profiles/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views
from .views import profile_view, get_author

app_name = 'profiles'

urlpatterns = [
	path('profile/', profile_view, name = 'user-profile'),
	path('profile/<pk>/', get_author, name = 'get-author'),
	#path('post/<pk>/', PostDetailView.as_view(), name='post-detail'),
]

profiles/models.py
from django.db import models
from django.contrib.auth import get_user_model
from PIL import Image

# Create your models here.

User = get_user_model()
username = User.username

class  Profile(models.Model):
	"""docstring for  Profiles"""
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	image = models.ImageField(default = 'profile_pics/default.png', upload_to = 'profile_pics')
	email = models.EmailField(blank = True, null = True)

	def __str__(self):
		return f'{self.user.username} Profile'

	def save(self, *args, **kwargs):
		super().save(*args, **kwargs)
		img = Image.open(self.image.path)
		if img.height>300 or img.width>300:
			#output_size = (300, 300)
			img.thumbnail(300, 300)
			img.save(self.image.path)

	def get_absolute_url(self):
		return reverse('profiles:get-author', kwargs = { 'pk' : self.user })

	# def get_update_url(self):
	# 	return reverse('myposts:post-update', kwargs = { 'pk' : self.pk })

	# def get_delete_url(self):
	# 	return reverse('myposts:post-delete', kwargs = { 'pk' : self.pk })

profiles/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email']


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['image']

profiles/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import UserRegisterForm, UserUpdateForm, ProfileUpdateForm
from .models import Profile
# Create your views here.

def profile_view(request):
	return render(request, 'profile.html', {})

def get_author(request):
    author = Profile.objects.get(username = request.user.username)
    return render(author, 'profile.html', {})

"""
def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Your account has been created! You are now able to log in')
            return redirect('login')
    else:
        form = UserRegisterForm()
    return render(request, 'users/register.html', {'form': form})


@login_required
def profile(request):
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST,
                                   request.FILES,
                                   instance=request.user.profile)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, f'Your account has been updated!')
            return redirect('profile')

    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)

    context = {
        'u_form': u_form,
        'p_form': p_form
    }

    return render(request, 'users/profile.html', context)

   """

templates/alternatefooter.html
<footer class="bg-dark" style="background-color: rgba(0, 0, 0, 1);">
  <!-- Footer content -->
  <div class="container">
    <div class="row">
      <div class="col-md-4">
        <div class="contact-details text-center p-3 text-white">
          <ul class="social-menu">
            <li class="list-inline-item"><a href="https://www.facebook.com/profile.php?id=100005843490736"><i class="fa fa-facebook"></i></a></li>
            <li class="list-inline-item"><a href="https://open.spotify.com/playlist/0ZTRlQpeU972TCHCfldVea?si=71OeJ6sgRziTvx0f7dwCPw&utm_source=copy-link&nd=1"><i class="fa fa-spotify"></i></a></li>
            <li class="list-inline-item"><a href="https://instagram.com/hereyndnow"><i class="fa fa-instagram"></i></a></li>
            <li class="list-inline-item"><a href="https://www.youtube.com/channel/UC63OgSKEa-FdMQB2dkMm2XA"><i class="fa fa-youtube"></i></a></li>
            <li class="list-inline-item"><a href="https://www.linkedin.com/in/r4hulchouhan"><i class="fa fa-linkedin"></i></a></li>
            <li class="list-inline-item"><a href="https://www.github.com/dopeprogr4mmer"><i class="fa fa-github"></i></a></li>
          </ul>
        </div>
      </div>
      <div class="col-md-4">
        <div class="text-center p-3 text-white">
          &copy; 2021 | <a href="/" style="color: skyblue; text-decoration: none;">travelrealindia</a>
        </div>
      </div>
      <div class="col-md-4">
        <div class="text-center p-3 text-white">
          <a href="/contact" style="color: skyblue; text-decoration: none;">Contact Us</a>
        </div>
      </div>
    </div>
  </div>
  <!-- Footer content -->
</footer>

templates/base.html
<!DOCTYPE html>
<html>

{% include 'head.html' %}
<body>
	{% block header %}
		{% include 'header.html' %}
	{% endblock header %}

	{% block content %}
	
	{% endblock content %}

	{% block center %}

	{% endblock center %}

	{% block footer%}
		{% include 'alternatefooter.html' %}
	{% endblock footer %}

	{% include 'scripts.html' %}

</body>

</html>

templates/categories.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
	<h1> This Are The posts </h1>
	{% for post in queryset %}
	<p>
		<a href = "{{ post.get_absolute_url }}"> {{ post.title }}</a>
	</p>
	{% endfor %}

{% endblock %}

templates/data_deletion.html
{% extends 'base.html' %}
{% load static %}
{% block center %}
  <div class="align-self-xl-center mx-auto">
    <h1>Data Deletion Instructions URL</h1>
    According to the Facebook Apps and Websites Platform rules, we have to provide User Data Deletion Callback URL or Data Deletion Instructions URL. If you want to delete your activities for the PalZtogo App, you can remove them by following the instructions below.<br><br>

    1. Go to Your Facebook Account’s “Settings & Privacy”, then click on ”Settings“.<br>
    2. Next, go to “Apps and Websites” where you will see all of the activity related to apps and websites that are 
    <br>linked to your Facebook account.<br>
    3. Select the option box for the PalZtogo App and click on the “Remove” button.<br>
    4. Mark the option boxes according to your preference and click on the “Remove” button.<br> 
    5. You’re done! You removed PalZtogo from your activities successfully. 
  </div>
{% endblock %}

templates/head.html
{% load static %}

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>travelrealindia</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="all,follow">
    <link rel="stylesheet" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'vendor/font-awesome/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/fontastic.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700">
    <link rel="stylesheet" href="{% static 'vendor/@fancyapps/fancybox/jquery.fancybox.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.default.css' %}" id="theme-stylesheet">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <link rel="shortcut icon" href="{% static 'img/lg.png' %}">
    <link rel="stylesheet" href="{% static 'css/prism.css' %}">
    <!-- Tweaks for older IEs--><!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]-->
</head>

templates/header.html
{% load static %}
<header class="header">
      <!-- Main Navbar-->
      <nav class="navbar navbar-expand-lg">
        <div class="search-area">
          <div class="search-area-inner d-flex align-items-center justify-content-center">
            <div class="close-btn"><i class="icon-close"></i></div>
            <div class="row d-flex justify-content-center">
              <div class="col-md-8">
                <form action="{% url 'myposts:search' %}">
                  <div class="form-group">
                    <input type="text" name = "q" id="search" placeholder="What are you looking for?">
                    <button type="submit" class="submit"><i class="icon-search-1"></i></button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
        <div class="container">
          <!-- Navbar Brand -->
          <div class="navbar-header d-flex align-items-center justify-content-between">
            <!-- Navbar Brand --><!--<a href="/" class="navbar-brand">travelrealindia.in</a>-->
            <a class="navbar-brand" href="/">
              <img src="{% static 'img/home.png' %}" alt="">
            </a>

            <!-- Toggle Button-->
            <button type="button" data-toggle="collapse" data-target="#navbarcollapse" aria-controls="navbarcollapse" aria-expanded="false" aria-label="Toggle navigation" class="navbar-toggler"><span></span><span></span><span></span></button>
          </div>
          <!-- Navbar Menu -->
          <div id="navbarcollapse" class="collapse navbar-collapse">
            <ul class="navbar-nav ml-auto">
              <li class="nav-item"><a href="/" class="nav-link ">HOME</a>
              </li>
              <li class="nav-item"><a href="/blog" class="nav-link ">BLOG</a>
              </li>
              <li class="nav-item"><a href="/gallery/" class="nav-link ">GALLERY</a>
              </li>
              <!--<li class="nav-item"><a href="/contact" class="nav-link ">CONTACT US</a>
              </li>-->
              {% if request.user.is_staff %}
              <li class="nav-item"><a href="{% url 'myposts:post-create' %}" class="nav-link ">CREATE</a>
              </li>
              {% endif %}
              {% if request.user.is_staff or request.user.is_authenticated %}
              <li class="nav-item"><a href="{% url 'account_logout' %}" class="nav-link ">LOGOUT </a>
              </li>        
              <li class="nav-item"><a class="pf_img" href="{% url 'profiles:user-profile' %}"><img src="{{ user.profile.image.url }}" alt=".."></a>
              </li>  
              {% else %}
              <li class="nav-item"><a href="{% url 'account_login' %}" class="nav-link ">LOGIN</a>
              </li>
              {% endif %}
            <div class="navbar-text"><a href="#" class="search-btn"><i class="icon-search-1"></i></a></div>
            {% comment %}<ul class="langs navbar-text"><a href="#" class="active">EN</a><span>           </span><a href="#">ES</a></ul>{% endcomment %}
          </div>
        </div>
      </nav>
    </header>

templates/index.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
    <!-- Hero Section-->
    <section style="background: url({% static 'img/f1.jpeg' %}); background-size: cover; background-position: center top" class="hero">
      <div class="container">
        <div class="row">
          <div class="col-lg-7">
            <h1>“A TRAVELER IS A LOCAL<br> OF THE GLOBE”</h1><!--<a href="#" class="hero-link">Discover More</a>-->
          </div>
        <!--</div><a href=".intro" class="continue link-scroll"><i class="fa fa-long-arrow-down"></i> Scroll Down</a>-->
      </div>
    </section>
    <!-- Intro Section-->
    <section class="intro">
      <div class="container">
        <div class="row">
          <div class="quote-wrap">
        	<blockquote class="quote-text"><p><h1>“Twenty years from now you will be more disappointed by the things that you didn't do than by the ones you did do. 
        	So throw off the bowlines. Sail away from the safe harbor. Catch the trade winds in your sails. Explore. Dream. Discover!”</h1></p>
        	<cite class="quote-author" style="text-align: right"><h5> HJackson Brown </h5><!--(no, not Mark Twain)--> </cite> </blockquote>
      	  </div><!-- end .quote-wrap -->
        </div>
      </div>
    </section>
  <!--<div class="jumbotron jumbotron-fluid">
  <div class="container">
  <h1 class="display-4">Hello, Travelers!</h1>
  <p class="lead">Planning a trip to somewhere. You know what's the worst enemy of a well planned trip is? Bad Weather!</p>
  <hr class="my-4">
  <p>Check the weather forecast now!(Beta)</p>
  <p class="lead">
    <a class="btn btn-primary btn-lg" href="{% url 'weatherapp:weather-view' %}" role="button">Go!</a>
  </p>
</div>
</div>-->
    <section class="featured-posts no-padding-top">
      <div class="container">
        <!-- Post-->
      {% for object in object_list %}
        <div class="row d-flex align-items-stretch">
          {% if forloop.counter|divisibleby:2 %}
          <div class="image col-lg-5"><img src="{{ object.thumbnail.url }}" alt="..."></div>
          {% endif %}
          <div class="text col-lg-7">
            <div class="text-inner d-flex align-items-center">
              <div class="content">
                <header class="post-header">
                  <div class="category">
                    {% for cat in object.categories.all %}
                      <a href="{% url 'myposts:category' cat.title %}">{{ cat.title }}</a>
                    {% endfor %}
                  </div>
                  <a href="{{ object.get_absolute_url }}">
                    <h2 class="h4">{{ object.title }}</h2></a>
                </header>
                <p>{{ object.overview }}</p>
                <footer class="post-footer d-flex align-items-center"><a href="{{ object.author.get_absolute_url }}" class="author d-flex align-items-center flex-wrap">
                    <div class="avatar"><img src="{{ object.author.profile_picture.url }}" alt="..." class="img-fluid"></div>
                    <div class="title"><span>{{ object.author }}</span></div></a>
                  <div class="date"><i class="icon-clock"></i>{{ object.timestamp|timesince}} ago</div>
                  <div class="comments"><i class="icon-comment"></i>{{ object.comment_count }}</div>
                </footer>
              </div>
            </div>
          </div>
          {% if not forloop.counter|divisibleby:2 %}
          <div class="image col-lg-5"><img src="{{ object.thumbnail.url }}" alt="..."></div>
          {% endif %}
        </div>
      {% endfor %}
        <!-- Post        -->
      </div>
    </section>
    <!-- Divider Section-->
    <section style="background: url({% static 'img/r1.jpeg' %}); background-size: cover; background-position: center center" class="hero">
      <div class="container">
        <div class="row">
          <div class="col-md-7">
            <h2>“The difference between living and existing is how much wonder you find in the beauty around you.”</h2><!--<a href="#" class="hero-link">View More</a>-->
          </div>
        </div>
      </div>
    </section>
    <!-- Latest Posts -->
    <section class="latest-posts"> 
      <div class="container">
        <header> 
          <h2>Latest from the blog</h2>
          <p class="text-big">Get the latest travel tales from our blog here.</p>
        </header>
        <div class="row">
          {% for obj in latest %}
          <div class="post col-md-4">
            <div class="post-thumbnai}"><!--<a href="{{ obj.get_absolute_url }}">--><img src="{{ obj.thumbnail.url }}" alt="..." class="img-fluid"><!--</a>--></div>
            <div class="post-details">
              <div class="post-meta d-flex justify-content-between">
                <div class="date">{{ obj.timestamp }}</div>
                <div class="category">
                  {% for cat in obj.categories.all %}
                      <a href="{% url 'myposts:category' cat.title %}">{{ cat }}</a>
                  {% endfor %}
                </div>
              </div><a href="{{ obj.get_absolute_url }}">
                <h3 class="h4">{{ obj.title }}</h3></a>
              <p class="text-muted">{{ obj.overview }}</p>
            </div>
          </div>
          {% endfor %}

          {% comment %}
          <div class="post col-md-4">
            <div class="post-thumbnail"><a href="post.html"><img src="{% static 'img/blog-2.jpg' %}" alt="..." class="img-fluid"></a></div>
            <div class="post-details">
              <div class="post-meta d-flex justify-content-between">
                <div class="date">20 May | 2016</div>
                <div class="category"><a href="#">Technology</a></div>
              </div><a href="post.html">
                <h3 class="h4">Diversity in Engineering: Effect on Questions</h3></a>
              <p class="text-muted">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore.</p>
            </div>
          </div>
          <div class="post col-md-4">
            <div class="post-thumbnail"><a href="post.html"><img src="{% static 'img/blog-3.jpg' %}" alt="..." class="img-fluid"></a></div>
            <div class="post-details">
              <div class="post-meta d-flex justify-content-between">
                <div class="date">20 May | 2016</div>
                <div class="category"><a href="#">Financial</a></div>
              </div><a href="post.html">
                <h3 class="h4">Alberto Savoia Can Teach You About Interior</h3></a>
              <p class="text-muted">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore.</p>
            </div>
          </div>
          {% endcomment %}
        </div>
      </div>
    </section>
    <!-- Newsletter Section-->
    <section class="newsletter no-padding-top">    
      <div class="container">
        <div class="row">
          <div class="col-md-6">
            <h2>Subscribe to Newsletter</h2>
            <p class="text-big">Stay updated with occasional email offers and news from <strong>travelreal!ndia</strong>.</p>
          </div>
          <div class="col-md-8">
            <div class="form-holder">
              <form action="." method = 'POST'>
                {% csrf_token %}
                <div class="form-group">
                  <input type="email" name="email" id="email" placeholder="Type your email address">
                  <button type="submit" class="submit">Subscribe</button>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </section>
    <!-- Gallery Section-->
    <section class="gallery no-padding">    
      <div class="row" id="gal">
        <div class="mix col-lg-3 col-md-3 col-sm-6">
          <div class="item"><a href="{% static 'img/ping1.jpeg' %}" data-fancybox="gallery" class="image"><img src="{% static 'img/ping1.jpeg' %}" alt="..." class="img-fluid">
              <div class="overlay d-flex align-items-center justify-content-center"><i class="icon-search"></i></div></a></div>
        </div>
        <div class="mix col-lg-3 col-md-3 col-sm-6">
          <div class="item"><a href="{% static 'img/ping2.jpeg' %}" data-fancybox="gallery" class="image"><img src="{% static 'img/ping2.jpeg' %}" alt="..." class="img-fluid">
              <div class="overlay d-flex align-items-center justify-content-center"><i class="icon-search"></i></div></a></div>
        </div>
        <div class="mix col-lg-3 col-md-3 col-sm-6">
          <div class="item"><a href="{% static 'img/ping3.jpeg' %}" data-fancybox="gallery" class="image"><img src="{% static 'img/ping3.jpeg' %}" alt="..." class="img-fluid">
              <div class="overlay d-flex align-items-center justify-content-center"><i class="icon-search"></i></div></a></div>
        </div>
        <div class="mix col-lg-3 col-md-3 col-sm-6">
          <div class="item"><a href="{% static 'img/ping4.jpeg' %}" data-fancybox="gallery" class="image"><img src="{% static 'img/ping4.jpeg' %}" alt="..." class="img-fluid">
              <div class="overlay d-flex align-items-center justify-content-center"><i class="icon-search"></i></div></a></div>
        </div>
      </div>
    </section>
{% endblock content %}

templates/post_delete.html
{% extends 'base.html' %}

{% block content %}

<form action = "." method = 'POST'>{% csrf_token %}
	<h1> Do you want to delete the post -"{{post.title}}? </h1>
	<p><input type = 'submit' value = 'Yes' /> <a href =  "{% url 'myposts:post-list' %}">Cancel</a></p>
</form>


{% endblock %}

templates/scripts.html
{% load static %}
<!-- JavaScript files-->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/popper.js/umd/popper.min.js' %}"> </script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'vendor/jquery.cookie/jquery.cookie.js' %}"> </script>
    <script src="{% static 'vendor/@fancyapps/fancybox/jquery.fancybox.min.js' %}"></script>
    <script src="{% static 'js/front.js' %}"></script>
    <script src="{% static 'js/prism.js' %}"></script>

templates/search_results.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
	<h1> This Are The Results For Your Search</h1>
	{% for post in queryset %}
	<p>
		<a href = "{{ post.get_absolute_url }}"> {{ post.title }}</a>
	</p>
	{% endfor %}

{% endblock %}

{% block footer%}
		{% include 'alternatefooter.html' %}
{% endblock footer %}

templates/sidebar.html
{% load static %}
<aside class="col-lg-4">
          <!-- Widget [Search Bar Widget]-->
          <div class="widget search">
            <header>
              <h3 class="h6">Search the blog</h3>
            </header>
            <form action="{% url 'myposts:search' %}" class="search-form">
              <div class="form-group">
                <input type="text" name = "q" placeholder="Search...">
                <button type="submit" class="submit"><i class="icon-search"></i></button>
              </div>
            </form>
          </div>
          <!-- Widget [Latest Posts Widget]        -->
          <div class="widget latest-posts">
            <header>
              <h3 class="h6">Latest Posts</h3>
            </header>
            <div class="blog-posts">
              {% for post in most_recent %}
              <a href="{{ post.get_absolute_url }}">
                <div class="item d-flex align-items-center">
                  <div class="image"><img src="{{ post.thumbnail.url }}" alt="..." class="img-fluid"></div>
                  <div class="title"><strong>{{ post.title }}</strong>
                    <div class="d-flex align-items-center">
                      <div class="views"><i class="icon-eye"></i>{{ post.view_count }}</div>
                      <div class="comments"><i class="icon-comment"></i>{{ post.comment_count }}</div>
                    </div>
                  </div>
                </div>
              </a>
              {% endfor %}
              </div>
          </div>
          <!-- Widget [Categories Widget]-->
          <div class="widget categories">
            <header>
              <h3 class="h6">Categories</h3>
            </header>
            {% for cat in category_count%}
            <div class="item d-flex justify-content-between">
              <a href="{% url 'myposts:category' cat.categories__title%}">{{ cat.categories__title}}</a><span>{{ cat.categories__title__count }}</span></div>
            {% endfor %}
          </div>
          <!-- Widget [Tags Cloud Widget]-->
</aside>