contactus/urls.py
from __future__ import unicode_literals
from django.conf.urls import url
from django.views.generic import TemplateView
from django.urls import path
from .views import ContactUsView

app_name = 'contactus'

urlpatterns = [
    path('contact/', ContactUsView.as_view(), {}, 'contactus'),
    path('contact/success/', TemplateView.as_view(
        template_name='contactus/contact_success.html'),
        {}, 'contactus-success'),
]

gallery/urls.py
from django.urls import path

from gallery.views import gallery_view #ImageView, ImageList, AlbumView, AlbumList, ImageCreate

app_name = 'gallery'
urlpatterns = [
    path('', gallery_view, name="gallery")
    #path('', AlbumList.as_view(), name='album_list'),
    #path('images/', ImageList.as_view(), name='image_list'),
    #path('image/<int:pk>/<slug>', ImageView.as_view(), name='image_detail'),
    #path('upload/', ImageCreate.as_view(), name='image_upload'),
    #path('album/<int:pk>/<slug>/', AlbumView.as_view(), name='album_detail'),
    #path('album/<int:apk>/<int:pk>/<slug>', ImageView.as_view(), name='album_image_detail'),
]

myblog/urls.py
from allauth.account import views as allauth_views
from django.conf.urls import url
from django.conf import settings
from django.views.static import serve
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from filebrowser.sites import site

handler404 = 'myposts.views.handler404'
handler500 = 'myposts.views.handler500'

urlpatterns = [
    url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
    path('admin/filebrowser/', site.urls),
	path('tinymce/',include('tinymce.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('accounts/login/', allauth_views.LoginView.as_view(template_name='login.html'), name='account_login'),
    path('', include('newsletter.urls', namespace = 'signups')),
    path('',include('myposts.urls', namespace = 'myposts')),
    path('',include('profiles.urls', namespace ='profiles')),
    path('',include('weatherapp.urls', namespace='weatherapp')),
    path('gallery/', include('gallery.urls')),
    path('',include('contactus.urls', namespace='contactus'))
]

myposts/urls.py
"""from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views
from .views import(
		index, 
		blog,
		search, 
		sort_by_category,
		post_detail,
		post_create,
		post_update,
		#PostUpdateView,
		post_delete
		#PostDeleteView
	) 


app_name = 'myposts'

handler404 = views.handler404 
handler500 = views.handler500

urlpatterns = [
	path('', index, name = 'index'),
	path('blog/', blog, name = 'post-list'),
	path('search/', search, name = 'search'),
	path('category/', sort_by_category, name = 'category'),
	path('post/<int:id>/', post_detail, name = 'post-detail'),
	path("create/", post_create, name ='post-create'),
	path("post/<int:id>/update", post_update, name = 'post-update'),
	path("post/<int:id>/delete", post_delete, name = 'post-delete')
]

urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
"""

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from .views import (
    index,
    search,
    blog,
    sort_by_category,
    data_deletion,
    #post_detail,
    #post_create,
    #post_update,
    #post_delete,
    PostDetailView,
    PostCreateView,
    PostUpdateView,
    PostDeleteView
)

app_name = 'myposts'


urlpatterns = [
    path('', index, name = 'index'),
    path('blog/', blog, name='post-list'),
    path('search/', search, name='search'),
    #path('category/', sort_by_category, name = 'category'),
    path('category/<category>', sort_by_category, name = 'category'),
    # path('create/', post_create, name='post-create'),
    path('data-deletion', data_deletion, name='data-deletion'),
    path('create/', PostCreateView.as_view(), name='post-create'),
    # path('post/<id>/', post_detail, name='post-detail'),
    path('post/<pk>/', PostDetailView.as_view(), name='post-detail'),
    # path('post/<id>/update/', post_update, name='post-update'),
    path('post/<pk>/update/', PostUpdateView.as_view(), name='post-update'),
    # path('post/<id>/delete/', post_delete, name='post-delete'),
    path('post/<pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
]

contactus/forms.py
from __future__ import unicode_literals
from django import forms
from django.conf import settings

SUBJECT_CHOICES = (
    ('-----', '-----'),
    ('info', 'Request more information'),
    ('contribute', 'Learn more about how to contribute'),
    ('bug', 'Correction or bug report'),
    ('other', 'Other')
)


if hasattr(settings, 'CONTACTUS_SUBJECT_CHOICES') and \
   settings.CONTACTUS_SUBJECT_CHOICES:
    SUBJECT_CHOICES = settings.CONTACTUS_SUBJECT_CHOICES


class ContactUsForm(forms.Form):
    name = forms.CharField(required=True, max_length=512)
    email = forms.EmailField(required=True)

    subject = forms.ChoiceField(
        required=True, choices=SUBJECT_CHOICES,
        widget=forms.Select(attrs={'class': "form-control"}))

    description = forms.CharField(
        widget=forms.Textarea(attrs={'class': "form-control"}),
        required=True)

    decoy = forms.CharField(widget=forms.Textarea, required=False)

    def clean(self):
        cleaned_data = super(ContactUsForm, self).clean()

        if cleaned_data.get('subject', None) == '-----':
            self._errors["subject"] = self.error_class([
                "Please specify a subject"])

        if 'decoy' in cleaned_data and len(cleaned_data['decoy']) > 0:
            self._errors["decoy"] = self.error_class([
                "Please leave this field blank"])

        return cleaned_data

contactus/views.py
from django.template import loader
from django.views.generic.edit import FormView
from contactus.forms import ContactUsForm, SUBJECT_CHOICES
import email
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
from email import encoders
import smtplib
import threading

recipients = ['supp0rt.travelrealindia@gmail.com']
bcc = ['rchouhan791@gmail.com']

def send(fromaddr, msg):
    smtp_server = "email-smtp.us-east-2.amazonaws.com"
    smtp_username = 'AKIA5H4YXSVOEZC3QUKP'
    smtp_password = 'BMP0VeHnbDxlTqJ6XoPt7K1fme67+RrcMh964z1i7xgx'
    smtp_port        = "2587"   #25, 587 or 2587
    smtp_do_tls      = True

    server      = smtplib.SMTP(
        host    = smtp_server,
        port    = smtp_port,
        timeout = 10
    )

    server.set_debuglevel(10)
    server.starttls()
    server.ehlo()
    server.login(smtp_username, smtp_password)
    server.sendmail(fromaddr, recipients + bcc, msg.as_string())
    server.quit()
    return True


class ContactUsView(FormView):
    template_name = 'contactus/contact.html'
    email_template_name = 'contactus/contact_notification_email.txt'
    form_class = ContactUsForm
    success_url = "/contact/success/"
    
    def get_initial(self):
        initial = super(ContactUsView, self).get_initial()
        if not self.request.user.is_anonymous:
            initial['name'] = self.request.user.get_full_name()
            initial['email'] = self.request.user.email
        initial['subject'] = '-----'

        return initial

    def form_valid(self, form):
        form_data = form.cleaned_data
        if not self.request.user.is_anonymous:
            form_data['username'] = self.request.user.username
        form_data['subject'] = dict(SUBJECT_CHOICES)[form_data['subject']]

        # POST to the support email
        tmpl = loader.get_template(self.email_template_name)
        content = tmpl.render(form_data)
        fromaddr         = "contact travelrealindia <contact.travelrealindia@gmail.com>"
        content_type     = "plain"
        msg              = email.mime.text.MIMEText( content, content_type, "utf-8" )
        msg["From"]      = fromaddr
        msg[ "Subject" ] = "Contact US Request/Feedback"
        msg[ "To" ]      = ",".join(recipients)
        task = threading.Thread(
                    target=send,
                    args=(fromaddr, msg)
                )
        task.start()

        return super(ContactUsView, self).form_valid(form)

contactus/templates/contactus/contact.html
{% extends "base.html" %}

{% block title %}Contact Us{% endblock %}

{% block content %}
    <style>
    .form-group .help-block {
        display: none;
    }
    .form-group.has-error .help-block {
        display: block;
    }
    input[name='decoy'],
    p.decoy {
        display: none !important;
    }
    </style>
    <div class="container bg-secondary text-white" style="float: none !important; display:  block; margin: 0 auto; padding-top: 15px; padding-bottom: 15px;">
    <div class="col-md-5 bg-dark text-white" style="float: none !important; display:  block; margin: 0 auto;">
        <br>
        <h2 class="title">Contact Us</h2>
        <br />
        <form action="." method="post" name="feedback" class="form-horizontal">{% csrf_token %}
            <div class="form-group {% if form.name.errors %}has-error{% endif %}">
                <label for="id_name" class="col-sm-2 control-label">Name</label>
                <div class="col-sm-8">
                    <input type="text" name="name" class="form-control"
                           id="id_name"
                           value="{% if form.data.name %}{{form.data.name}}{% else %}{{form.initial.name}}{% endif %}" />
                    <p class="help-block">Name is a required field</p>
                </div>
            </div>    
            <div class="visualclear"></div>
            <div class="form-group {% if form.email.errors %}has-error{% endif %}">
                <label for="id_email" class="col-sm-4
                 control-label">E-mail Address</label>
                <div class="col-sm-8">
                    <input class="form-control" type="text" name="email"
                           id="id_email"
                           value="{% if form.data.email %}{{form.data.email}}{% else %}{{form.initial.email}}{% endif %}" />
                    <div class="visualclear"></div>                
                    <p class="help-block">A valid e-mail address is required.</p>
                </div>
            </div>
            <br />
            <div class="visualclear"></div>
            <div class="form-group {% if form.subject.errors %}has-error{% endif %}">
                <label for="id_subject"  class="col-sm-2 control-label">Subject</label>
                <div class="col-sm-12">
                    {{form.subject}}
                    <p class="help-block">Subject is a required field.</p>
                </div>
            </div>
            <br />
            <div class="form-group {% if form.description.errors %}has-error{% endif %}">
                <label for="id_description" class="col-sm-2 control-label">Description</label>
                <div class="col-sm-12">
                    {{form.description}}
                    <p class="help-block">Description is a required field.</p>
                </div>
            </div>
            <div class="form-group {% if form.decoy.errors %}has-error{% endif %}">
                <input type="text" name="decoy" value="" placeholder="Please leave blank" autofill="off" />
                <p class="help-block decoy">If you can see the decoy field, please leave it blank.</p>
            </div>

            <div class="col-md-8">
                <input class="btn btn-primary" type="submit" value="Send Feedback"/>
            </div>
            <br>
        </form>
    </div>
</div>
{% endblock %}

contactus/templates/contactus/contact_success.html
{% extends 'base.html' %}
{% load static %}
{% block center %}
  <div class="align-self-xl-center mx-auto" style="padding-left: 34%; padding-top: 15%; padding-bottom: 15%;">
    <font size="+3"><strong>Thanks!</strong></font>
    <br>
    <p>We appreciate your feedback.<br />
    Someone from the team will be in touch with you shortly.</p>
    <a class="btn btn-primary" href="{% url 'myposts:index' %}">Homepage</a>
    <!--<a class="btn btn-primary" href="">Try Again</a>-->
  </div>
{% endblock %}